разметка
htmlacademy-htmlcss/2074401-sedona-34 pull request #2
Opened 2022-06-05 16:54 UTC by SukharevIgor

2022-06-06 17:33 UTC, andreysgra requested changes
То, что касается графики, не проверял, так как это уже следующее задание [Графика для всех страниц](https://up.htmlacademy.ru/htmlcss/34/tasks/5). Но вопросы по наименованию файлов и папок нужно исправить.

И на всякий случай: за данной ссылкой
![image](https://user-images.githubusercontent.com/17790771/172214354-fba839f5-38c0-434d-bab2-f673124e9d4d.png)
гитхаб скрывает часть замечаний.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +              <img alt="домой" src="Images\Hotels\breadcrubs-home.svg">
Есть ошибки валидации HTML. В данном случае использован обратный слеш в пути к файлу. Проверить можно [здесь](https://validator.w3.org/nu/#textarea).

Также общее замечание по именованию файлов. Это критерий [PROJ-03](https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-03). Нужно внести исправления в HTML, а также переименовать названия файлов в соответствии с требованием критерия.

У git есть одна особенность - если вы изменяете регистр букв в названии файла при этом не изменяя название, то он это игнорирует. Просто измените название файлов. Либо другой вариант - переносите файлы из проекта в другое место. Делаете коммит, изменяете регистр букв в названии, возвращаете файлы в проект, снова делаете коммит.

2022-06-06 17:33 UTC, andreysgra commented on index.html
> +      <span class="visually-hidden home">
Совсем непонятно, зачем здесь этот тег. Также на главной странице есть ошибки валидации HTML.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +      <span class="visually-hidden home">
Зачем ссылку оборачивать тегом `span`? Чтобы в элемент поместить текст, которого нет в макете, но текст нужен для скринридера, текст оборачивают в `span` с классом `visually-hidden`. Текст, но не сам элемент. Должно быть так (класс `home` тут не нужен):
```
<a class="navigation-logo" href="index.html">
  <span class="visually-hidden">На главную</span>
</a>
```
Такой вариант был бы правильным, если бы внутри ссылки не было бы логотипа. Логотип является контентным изображением, следовательно его нужно добавить тегом `img`. (Про контентные и декоративные изображения можно почитать [здесь](https://htmlacademy.ru/blog/articles/content-or-decor-img)). А так как подпись для изображения размещают в атрибуте `alt`, то `span` тут фактически не нужен.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +          <button name="want">Хочу сюда</button>
Это ссылка, которая по внешнему виду похожа на кнопку. Ссылка, потому что предполагается переход на другую страницу сайта.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +        <section>
С строке 49 есть тег `section` с классом `catalog-header`. Следом вы добавляете ещё одну секцию. `section` это смысловая часть раздела сайта и лишних секций добавлять не нужно. Здесь подойдёт `div`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +          <h1 class="catalog-header-title  ">Гостинницы Седоны</h1>
```suggestion
          <h1 class="catalog-header-title  ">Гостиницы Седоны</h1>
```
Чтобы не допускать ошибок и опечаток, текст лучше копировать непосредственно из макета:
![image](https://user-images.githubusercontent.com/17790771/170198125-19caae07-33ed-40df-a47d-c0ea4c76ba90.png)

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +          <ol class="breadcrumbs">
`ol` - это нумерованный список. Какой смысл в навигации использовать нумерацию? Просто `ul`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +              <a class="breadcrumbs-link visually-hidden" href="index.html">Главная</a>
Даже если этот домик
![image](https://user-images.githubusercontent.com/17790771/172210946-d1a71225-0239-4f2a-8abd-7866591bcd52.png)
не рассматривать, как изображение декоративное (но оно больше похоже именно на него), то `img` должен быть внутри ссылки, а не отдельно от неё.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +              <a class="breadcrumbs-link">Гостинницы</a>
```suggestion
              <a class="breadcrumbs-link">Гостиницы</a>
```

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +                      <input class="control-input" type="checkbox" name ="Parking" checked>
Заглавные буквы в значении атрибута `name`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +                    <input class="control-input" type="checkbox" name ="WI-FI">
Заглавные буквы в значении атрибута `name`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +                    <input class="control-input" type="radio" name="product-group" value="Hotel" checked>
Заглавные буквы в значении атрибута `value`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +                    <input class="control-input" type="radio" name="product-group" value="Motel">
Заглавные буквы в значении атрибута `value`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +                    <input class="control-input" type="radio" name="product-group" value="Apartments">
Заглавные буквы в значении атрибута `value`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +                <label><input type="range" min="0" max="9000" value="7000" class="slider"></label>
Нет. `range` здесь не подходит, так как данный элемент интерфейса имеет два ползунка, а у `range` всего один. Пока этот элемент размечать не нужно, его вёрстка будет рассмотрена ближе к концу курса.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +              <input type="reset" value="Применить">
Вместо `input` используйте тег `button` с соответствующим значением `type`. (Атрибут `value` к тегу `button` применять не нужно).

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +          </select>
Есть критерий про оформление кода [PROJ-01](https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01). Нужно следовать правилам, описанным в кодгайде.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +          <h2>Найдено гостиниц: 38</h2>
Это явно не заголовок. Просто текст в теге `p`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +            <span class="hotel-card-title">Amara Resort & Spa</span>
А может это всё-таки заголовок? (Название гостиницы, однако).
![image](https://user-images.githubusercontent.com/17790771/172212305-f7acd771-8fae-44fb-b2a1-0a1e5d32ab02.png)

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +            <a class="pagination-link pagination-current pagination-disabled">1</a>
Класс `pagination-disabled` - лучше `pagination-current`, так как у ссылки нет состояния `disabled`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +            <input class="field" placeholder="Ващ e-mail" type="email" name="newsletter-email" id="newsletter-email" required>
```suggestion
            <input class="field" placeholder="Ваш e-mail" type="email" name="newsletter-email" id="newsletter-email" required>
```

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +          <input type="submit" value="Подписаться">
Вместо `input` используйте тег `button`.

2022-06-06 17:33 UTC, andreysgra commented on catalog.html
> +      </a>
Логотип - изображение контентное. Нужен тег `img` внутри ссылки.

2022-06-06 17:33 UTC, andreysgra commented on index.html
> +
Это контентное изображение. Нужно добавить в разметку.
![image](https://user-images.githubusercontent.com/17790771/172213205-c213788d-42cc-4bbb-a9ca-179117d821c6.png)

2022-06-06 17:33 UTC, andreysgra commented on index.html
> +      </ul>
Блок описывающий 5 причин логичнее разметить одним списком `ol` (происходит перечисление причин у которых есть нумерация).
![image](https://user-images.githubusercontent.com/17790771/172213521-f774cfee-3d87-4832-aaa9-0158d0166890.png)

А вот этот блок
![image](https://user-images.githubusercontent.com/17790771/170199124-f8e42e26-a030-4034-bf6c-8776a68623c3.png)
нужно разметить отдельным списком, который будет вложенным в первый элемент `li` списка `ol`:
```
<ol class="feature-list"
  <li class="feature-item-real-town">
    <h2 class="real-town">Настоящий городок</h2>
    <p class="irem-one">— №1 —</p>
    <p class="real-town-text">Седона — не аттракцион для туристов, там течет своя жизнь</p>
    <img src=" " alt="Улица городка">

    <ul>
      <li class="housing">
        <h3 class="housing">Жильё</h3>
        <p class="housing-text">Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
      </li>
      <!-- ... -->
    </ul>
  </li>
  <!-- ... -->
</ol>
```

2022-06-06 17:33 UTC, andreysgra commented on index.html
> +        <a class="button button-all" href="catalog.html">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
Текст в разметке не нужно писать заглавными буквами (с заглавной буквы начинается только первое слово в предложении).

2022-06-10 07:28 UTC, andreysgra requested changes
Большую часть замечаний вы исправили и это хорошо, но всё же недочёты остались.
1. То, что вы исправили на странице пулл реквеста помечено мною следующим образом:
![image](https://user-images.githubusercontent.com/17790771/173012790-28338bc6-9513-483e-99de-3445ccc0b2d2.png)
Что не исправлено, находится в таком статусе:
![image](https://user-images.githubusercontent.com/17790771/173012912-337a4aa4-df0d-43b2-9743-60938898b70b.png)
Поэтому обратите внимание на эти замечания (что-то может находиться за этой ссылкой
![image](https://user-images.githubusercontent.com/17790771/172214354-fba839f5-38c0-434d-bab2-f673124e9d4d.png))
2. По прежнему есть ошибки валидации HTML.
3. Есть вопросы по именованию файлов и папок.

2022-06-10 07:28 UTC, andreysgra commented on catalog.html
> +          <button>Подписаться</button>
У кнопки отсутствует атрибут `type`. Критерий [HTML-03](https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-03).

2022-06-13 11:23 UTC, SukharevIgor commented on index.html
> +        <a class="button button-all" href="catalog.html">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</a>
Это было исправлено!

2022-06-13 11:23 UTC, SukharevIgor commented on catalog.html
> +              <img alt="домой" src="Images\Hotels\breadcrubs-home.svg">
Этот пункт я удалил и этой ошибки быть не может уже.

2022-06-15 06:48 UTC, andreysgra commented on catalog.html
> +              <img alt="домой" src="Images\Hotels\breadcrubs-home.svg">
Да, этот пункт вы удалили и здесь ошибки быть не может. Но в других местах ошибки валидации есть. Я в этом комментарии давал ссылку на сервис проверки HTML.

1. Открываете в редакторе кода к примеру страницу каталога. Копируете всё содержимое. Вставляете его на [этой странице](https://validator.w3.org/nu/#textarea), нажимаете кнопку `Check`.
2. Проверка страницы каталога выдаёт такие ошибки (на скриншоте показал часть ошибок):
![image](https://user-images.githubusercontent.com/17790771/173760281-f0f0b715-2340-48de-8b66-67a4b67207c4.png)

То, что помечено словом `Error` и выделено красным цветом, является ошибкой и обязательно к исправлению. Места, помеченные словом `Warning` можно не исправлять.

Главная страница тоже имеет большое количество ошибок валидации.
![image](https://user-images.githubusercontent.com/17790771/173760673-8dbb4aef-e34e-4fa8-9424-fbc62917f254.png)

Если что-то непонятно из описания валидатора, можете спросить у меня. У вас в основном ошибки в относительном пути к файлам. В HTML, как и в Unix-системах, принято использовать слеш `/`, а не в стиле Windows `\`, как сделано у вас.

2022-06-15 06:56 UTC, andreysgra requested changes
В [этом](https://github.com/htmlacademy-htmlcss/2074401-sedona-34/pull/2#discussion_r890346660) комментарии самой первой проверки я написал подробнее, как найти ошибки валидации. В самом комментарии описано, как исправить ошибку именования файлов (у вас много файлов и папок имеют заглавные буквы в названии) - это второй и третий абзацы.

Папка images начинается с заглавной буквы:
![image](https://user-images.githubusercontent.com/17790771/173761838-09b45872-1d5a-4e55-98e7-f67ba95f1264.png)
Эти папки тоже:
![image](https://user-images.githubusercontent.com/17790771/173761924-5b8cbdce-5d81-47c1-b053-027998ef4db8.png)
Здесь видим файл, в названии которого есть заглавные буквы
![image](https://user-images.githubusercontent.com/17790771/173762091-9f137346-5610-4f2b-9196-fd257c143d13.png)
И так далее, Исправить нужно всё, а не только то, что указал в примерах.

Надеюсь, что следующая попытка будет удачной.

2022-06-18 12:26 UTC, merged